import { Fustat } from "next/font/google";
import "./globals.css";
import Loader from "@/components/Loader";
import LenisProvider from "@/components/LenisProvider";

const fustatSans = Fustat({
  variable: "--font-fustat-sans",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Beast & Fur | Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fustatSans.variable} antialiased`}>
        <Loader />
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
